### ISSUE TITLE
WA貌似在vanilla没有效果

### ISSUE THREAD

**Issue by takaqiao** [icaca/WclPlayerScore-Vanilla#1]
RT 因为我看到desc里面有写WA但实际上好像没有效果~ 不知道能不能失陪一下 感谢！

**Comment by icaca** [comment]
wa的代码估计要修改下，我没有去亚服，所以测试不了。

**Comment by takaqiao** [comment]
收到 可以提供测试的代码我来测试嘛 或者您告诉我哪里一块需要修改我研究一下

**Comment by icaca** [comment]
1. 确认wcl插件数据是否正常
2. wa打开设置页面，截图发我看下。
3. wa里如果有代码的可以粘贴过来。

**Comment by takaqiao** [comment]
1.mouseover时是正常的
2.
![image](https://github.com/icaca/WclPlayerScore-Vanilla/assets/13859193/33ed6181-abc4-4e8b-9c09-6c8ccda8a953)
![image](https://github.com/icaca/WclPlayerScore-Vanilla/assets/13859193/96db30e3-fcd7-4818-b4ab-3b3ccb62704e)
3.这一项没理解 是指别的WA吗？

**Comment by icaca** [comment]
嗯 要看下naxx怎么定义的，换成你要的副本就可以了

**Comment by takaqiao** [comment]
是的 我之前研究了一下 也看了下插件的代码 主要是不知道黑暗深渊是不是BFD？

**Comment by takaqiao** [comment]
> 是的 我之前研究了一下 也看了下插件的代码 主要是不知道黑暗深渊是不是BFD？

我看NAXX是WA调取数据库里的相关数据 但是不知道为什么BFD不行

**Comment by icaca** [comment]
插件里都是数据，没有BFD的定义。你先找找naxx插件怎么定义的

**Comment by icaca** [comment]
STOP_Database  WP_Database 关键字是这两个，这2个是wcl插件提供的数据

**Comment by takaqiao** [comment]
> STOP_Database WP_Database 关键字是这两个，这2个是wcl插件提供的数据

收到 我研究一下 谢谢！

**Comment by takaqiao** [comment]
谢谢大佬 研究了一下 搞定了~ 请问sod不放WCL分数是有什么特殊原因嘛

**Comment by icaca** [comment]
> 谢谢大佬 研究了一下 搞定了~ 请问sod不放WCL分数是有什么特殊原因嘛

没听明白

**Comment by takaqiao** [comment]
> > 谢谢大佬 研究了一下 搞定了~ 请问sod不放WCL分数是有什么特殊原因嘛
> 
> 没听明白

就是赛季模式为什么只有全明星 不包含WCL分数，全球榜等等

**Comment by icaca** [comment]
香草有2种模式，一种进度到naxx，一种是plus进度是诺莫瑞根，所以在处理的时候会麻烦一点。遇到没有分数的情况可以反馈下哪个服务器

**Comment by takaqiao** [comment]
> 香草有2种模式，一种进度到naxx，一种是plus进度是诺莫瑞根，所以在处理的时候会麻烦一点。遇到没有分数的情况可以反馈下哪个服务器

了解 谢谢大佬！
